const {
  API_HOST,
  API_PORT,
  AUTH_DISABLED: PROVIDED_AUTH_DISABLED = "false",
  HOST: PROVIDED_HOST = "0.0.0.0",
  PORT: PROVIDED_PORT = "3440",
} = process.env
const AUTH_DISABLED = PROVIDED_AUTH_DISABLED === "true"

const PORT = parseInt(API_PORT || PROVIDED_PORT)
const HOST = API_HOST || PROVIDED_HOST

export { AUTH_DISABLED, PORT, HOST }
